# -*- coding: utf-8 -*-
"""8_puzzle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a4D2uGwEInKhE4CWtETmdbugw3vR5itS
"""

import heapq
import copy

# Define the goal state
GOAL_STATE = [
    ['1', '2', '3'],
    ['4', '5', '6'],
    ['7', '8', '_']
]

def find_position(state, element):
    """Finds the row and column of a given element in the 3x3 grid."""
    for r in range(3):
        for c in range(3):
            if state[r][c] == element:
                return (r, c)
    return None

def manhattan_distance(state):
    """Calculates h(n): the sum of Manhattan distances of tiles from their goal positions."""
    distance = 0
    for r in range(3):
        for c in range(3):
            tile = state[r][c]
            if tile != '_':
                # Find where this tile should be in the goal state
                goal_r, goal_c = find_position(GOAL_STATE, tile)
                distance += abs(r - goal_r) + abs(c - goal_c)
    return distance

class PuzzleNode:
    """Represents a state in the search tree."""
    def __init__(self, state, parent=None, action=None, g_cost=0):
        self.state = state
        self.parent = parent
        self.action = action
        self.g_cost = g_cost
        self.h_cost = manhattan_distance(state)
        self.f_cost = self.g_cost + self.h_cost

    # Defining comparison operators for the priority queue (frontier)
    def __lt__(self, other):
        return self.f_cost < other.f_cost

def get_actions(blank_pos):
    """Returns valid moves based on the current blank position."""
    r, c = blank_pos
    moves = []
    if r > 0: moves.append(('UP', -1, 0))
    if r < 2: moves.append(('DOWN', 1, 0))
    if c > 0: moves.append(('LEFT', 0, -1))
    if c < 2: moves.append(('RIGHT', 0, 1))
    return moves

def get_child_node(node, action_info):
    """Generates a successor state (child node)."""
    action_name, dr, dc = action_info
    state_copy = copy.deepcopy(node.state)
    r, c = find_position(state_copy, '_')
    new_r, new_c = r + dr, c + dc

    # Swap blank with the target tile
    state_copy[r][c], state_copy[new_r][new_c] = state_copy[new_r][new_c], state_copy[r][c]

    return PuzzleNode(
        state=state_copy,
        parent=node,
        action=action_name,
        g_cost=node.g_cost + 1
    )

def print_state(state):
    """Utility to display the grid state."""
    for row in state:
        print(" ".join(row))
    print()

def solve_8_puzzle(initial_state):
    """Solves the 8-puzzle using A* Search."""
    # Open list / Frontier ordered by f(n)
    frontier = []
    # Unique counter to act as tie breaker in heapq if f_costs are equal
    counter = 0

    root = PuzzleNode(initial_state)
    heapq.heappush(frontier, (root.f_cost, counter, root))
    counter += 1

    # Closed list / Explored set stored as immutable tuples
    explored = set()

    while frontier:
        _, _, current_node = heapq.heappop(frontier)

        # Check for goal state
        if current_node.state == GOAL_STATE:
            # Reconstruct path
            path = []
            curr = current_node
            while curr is not None:
                path.append(curr)
                curr = curr.parent
            path.reverse()

            # Print results
            print("Initial State:")
            print_state(path[0].state)

            for i in range(1, len(path)):
                print(f"Move {i}: {path[i].action}")
                print_state(path[i].state)

            print("Goal State Reached")
            print(f"Solution Cost = {current_node.g_cost}")
            return

        # Convert state matrix to tuple of tuples to be hashable in set
        state_tuple = tuple(tuple(row) for row in current_node.state)

        if state_tuple not in explored:
            explored.add(state_tuple)

            blank_pos = find_position(current_node.state, '_')
            for action in get_actions(blank_pos):
                child = get_child_node(current_node, action)
                child_tuple = tuple(tuple(row) for row in child.state)

                if child_tuple not in explored:
                    heapq.heappush(frontier, (child.f_cost, counter, child))
                    counter += 1

    print("No solution exists.")

# Demo using the example from your instructions
initial_configuration = [
    ['1', '2', '3'],
    ['5', '_', '6'],
    ['4', '7', '8']
]

solve_8_puzzle(initial_configuration)

