# -*- coding: utf-8 -*-
"""TIC_TAC_TOE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oR1OH-1itdBYfB4rX6b--wzUX9qHyYmx

### Rule-Based (Heuristic) Tic-Tac-Toe Decision Maker
This approach avoids recursive function calls entirely, making it highly efficient and much easier to read, debug, and understand.
"""

import random

# Board indices layout:
# 0 | 1 | 2
# ---------
# 3 | 4 | 5
# ---------
# 6 | 7 | 8

WINNING_COMBINATIONS = [
    (0, 1, 2), (3, 4, 5), (6, 7, 8), # Rows
    (0, 3, 6), (1, 4, 7), (2, 5, 8), # Columns
    (0, 4, 8), (2, 4, 6)             # Diagonals
]

CORNERS = [0, 2, 6, 8]
SIDES = [1, 3, 5, 7]
CENTER = 4

def get_winning_or_blocking_move(board, player_symbol):
    """Finds a move that completes a line of 3 for the given symbol."""
    for combo in WINNING_COMBINATIONS:
        values = [board[i] for i in combo]
        if values.count(player_symbol) == 2 and values.count(' ') == 1:
            empty_index = combo[values.index(' ')]
            return empty_index
    return None

def rule_based_decision(board, ai_symbol, human_symbol):
    """
    Returns the best move index for the AI using a prioritized heuristic rule list.
    """
    # Rule 1: Win if possible
    move = get_winning_or_blocking_move(board, ai_symbol)
    if move is not None:
        return move

    # Rule 2: Block human from winning
    move = get_winning_or_blocking_move(board, human_symbol)
    if move is not None:
        return move

    # Rule 3: Take Center
    if board[CENTER] == ' ':
        return CENTER

    # Rule 4: Take opposite corner if human is in a corner
    opposite_corners = {0: 8, 8: 0, 2: 6, 6: 2}
    for corner, opp in opposite_corners.items():
        if board[corner] == human_symbol and board[opp] == ' ':
            return opp

    # Rule 5: Take any empty corner
    empty_corners = [c for c in CORNERS if board[c] == ' ']
    if empty_corners:
        return random.choice(empty_corners)

    # Rule 6: Take any empty side
    empty_sides = [s for s in SIDES if board[s] == ' ']
    if empty_sides:
        return random.choice(empty_sides)

    return None

"""### Heuristic Game Loop
You can now play against this rule-based heuristic engine instantly below!
"""

def run_heuristic_game():
    board = [' ' for _ in range(9)]
    human = 'X'
    ai = 'O'

    def show():
        print(f"\n{board[0]} | {board[1]} | {board[2]}\n--+---+--\n{board[3]} | {board[4]} | {board[5]}\n--+---+--\n{board[6]} | {board[7]} | {board[8]}\n")

    print("Heuristic Tic-Tac-Toe Game Active (You = X, AI = O)")
    show()

    for turn in range(9):
        if turn % 2 == 0:
            # Human turn
            while True:
                try:
                    move = int(input("Enter position (0-8): "))
                    if 0 <= move <= 8 and board[move] == ' ':
                        board[move] = human
                        break
                    print("Position taken or invalid!")
                except ValueError:
                    print("Please enter a number between 0 and 8.")
        else:
            # AI turn
            print("AI is computing move based on rules...")
            move = rule_based_decision(board, ai, human)
            if move is not None:
                board[move] = ai
                print(f"AI played at {move}")

        show()

        # Check winner
        for combo in WINNING_COMBINATIONS:
            if board[combo[0]] != ' ' and board[combo[0]] == board[combo[1]] == board[combo[2]]:
                print(f"Player {board[combo[0]]} wins!")
                return

    print("It's a draw!")

# Run the game:
run_heuristic_game()

"""### Single Move Predictor
This function takes any current board state (where `'X'` is the human, `'O'` is the computer, and `' '` is empty) and performs just the computer's turn.
"""

def check_game_winner(board, symbol):
    """Helper to check if a specific player has won the game."""
    for combo in WINNING_COMBINATIONS:
        if board[combo[0]] == board[combo[1]] == board[combo[2]] == symbol:
            return True
    return False

def make_computer_move(current_board):
    """
    Accepts current_board as a list of 9 elements or a string.
    Cleans the input (removing commas), processes the move,
    and reports if the game has ended (Win, Loss, or Draw).
    """
    # If the input is a string, remove commas to handle comma-separated values
    if isinstance(current_board, str):
        cleaned_board = current_board.replace(',', '')
    else:
        cleaned_board = list(current_board)

    board_list = list(cleaned_board)

    # Pad short board states with empty spaces
    if len(board_list) < 9:
        board_list += [' '] * (9 - len(board_list))
    elif len(board_list) > 9:
        board_list = board_list[:9]

    print("Current Board State:")
    print(f"{board_list[0]} | {board_list[1]} | {board_list[2]}\n--+---+--\n{board_list[3]} | {board_list[4]} | {board_list[5]}\n--+---+--\n{board_list[6]} | {board_list[7]} | {board_list[8]}\n")

    # Check if someone has already won prior to computer's move
    if check_game_winner(board_list, 'X'):
        print("Human (X) has already won this game!")
        return
    if check_game_winner(board_list, 'O'):
        print("Computer (O) has already won this game!")
        return
    if ' ' not in board_list:
        print("The game is already a draw!")
        return

    # Calculate and make the computer's move (O)
    move = rule_based_decision(board_list, ai_symbol='O', human_symbol='X')

    if move is not None:
        board_list[move] = 'O'
        print(f"Computer plays 'O' at position {move}. Updated Board:")
        print(f"{board_list[0]} | {board_list[1]} | {board_list[2]}\n--+---+--\n{board_list[3]} | {board_list[4]} | {board_list[5]}\n--+---+--\n{board_list[6]} | {board_list[7]} | {board_list[8]}\n")

        # Analyze and output final game state
        if check_game_winner(board_list, 'O'):
            print("Result: Computer (O) wins!")
        elif ' ' not in board_list:
            print("Result: It's a draw!")
        else:
            print("Result: Game is still active. Your turn!")
    else:
        print("No valid moves left on the board!")

"""### Test the Function
Let's test the function with a custom board state where `X` is at position 0 (top-left) and position 8 (bottom-right).
"""

test_board = input("Enter a 9-character board state (use 'X', 'O', or spaces ' '): ")
make_computer_move(test_board)



test_board = input("Enter a 9-character board state (use 'X', 'O', or spaces ' '): ")
make_computer_move(test_board)

test_board = input("Enter a 9-character board state (use 'X', 'O', or spaces ' '): ")
make_computer_move(test_board)

