# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pHxmD29YWD2dpZEOiiCMaau7vICcbtQF
"""

x="nayana"
print(x)

age = 25

print("Age:", age)

height = 5.11

print("Height:", height)

message = "Hello, world!"

print("Message:", message)


is_student = True

print("Is Student:", is_student)

numbers = [1, 2, 3, 4, 5]

print("Numbers:", numbers)

# Tuples

coordinates = (10, 20)

print("Coordinates:", coordinates)

# Dictionaries

person = {"name": "Alice", "age": 30}

print("Person:", person)

# Arithmetic Operations

sum = 12+13

print("Sum:", sum)

difference = 110 - 4

print("Difference:", difference)

product = 16 * 2

print("Product:", product)

quotient = 120 / 3

print("Quotient:", quotient)

remainder = 15 % 4

print("Remainder:", remainder)

power = 2 ** 3

print("Power:", power)

is_equal = (5 == 5)

print("Is Equal:", is_equal)

is_greater = (10 > 5)

print("Is Greater:", is_greater)

is_less_or_equal = (15 <= 20)

print("Is Less or Equal:", is_less_or_equal)

# Logical Operations

and_result = (True and False)

print("AND Result:", and_result)

or_result = (True or False)

print("OR Result:", or_result)

not_result = (not True)

print("NOT Result:", not_result)

x = 10

if x > 5:

print("x is greater than 5")

elif x == 5:

print("x is equal to 5")

else:

print("x is less than 5")

numbers = [1, 2, 3, 4, 5]

for num in numbers:

  print(num)

x = 0

while x < 5:

  print(x)
  x += 1

num = int(input("Enter a number: "))

factorial = 1

for i in range(1, num + 1):

  factorial *= i

print("Factorial of", num, "is", factorial)

